### ISSUE TITLE
Gestion des espaces de nommage

### ISSUE THREAD

**Issue by alhyss** [ecolabdata/ckanext-ecospheres#5]
Un [commit](https://github.com/ecolabdata/ckanext-ecospheres/commit/276a8e90c01ec079199718cefe4760b619c0138d#diff-e8a5fc93a044df6c4a58eb4b605662c75dbff2650c16207c757cce31b3fd6114) a ajouté la définition de deux espaces de nommage en dur dans le module `vocabulary.parser.utils`.

```python
from rdflib import (
    Graph, URIRef, Literal, 
)
from rdflib.namespace import Namespace, RDFS, RDF, SKOS
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
DCT = Namespace("http://purl.org/dc/terms/")
```

au lieu de : 
```python
from rdflib import (
    Graph, URIRef, Literal, SKOS, RDF, RDFS,
    DCTERMS as DCT, FOAF
)
```

Est-ce que cet import posait problème avec la version de RDFLib utilisée par CKAN ?

**Comment by asboukerram** [comment]
Un commit a ajouté la définition de deux espaces de nommage en dur dans le module vocabulary.parser.utils.

    from rdflib import (
        Graph, URIRef, Literal, 
    )
    from rdflib.namespace import Namespace, RDFS, RDF, SKOS
    FOAF = Namespace("http://xmlns.com/foaf/0.1/")
    DCT = Namespace("http://purl.org/dc/terms/")

au lieu de :

    from rdflib import (
        Graph, URIRef, Literal, SKOS, RDF, RDFS,
        DCTERMS as DCT, FOAF
    )



-  En effet, je pense cela est du à une erreur de ma part, il faut garder le second bout de code.
