### ISSUE TITLE
Suppression du répertoire `vocabularies` de la branche `develop`

### ISSUE THREAD

**Issue by alhyss** [ecolabdata/ckanext-ecospheres#6]
L'ex-répertoire [`vocabularies`](https://github.com/ecolabdata/ckanext-ecospheres/tree/develop/vocabularies) de la branche `develop` a été supprimé lors de la fusion des branches `develop` et `spatial` - cf. #2.

Après examen, il s'avère qu'il ne contenait absolument pas la sérialisation JSON des vocabulaires, mais des fichiers de données brutes. Leur suppression a-t-elle des incidences ?

**Comment by asboukerram** [comment]
je confirme ça n'a aucune incidence

**Comment by alhyss** [comment]
Parfait !
